SELECT COUNT(*)COUNTRY FROM COUNTRY;
SELECT COUNT(*)CONTINENT FROM CONTINENT;
SELECT COUNT(*)STATUS FROM STATUS;
SELECT COUNT(*)PILOT FROM PILOT;
SELECT COUNT(*)PASSENGER FROM PASSENGER;
SELECT COUNT(*)DATE FROM DATE_FL;
SELECT COUNT(*)ARRIVAL FROM ARRIVAL;
SELECT COUNT(*)FLIGHT FROM FLIGHT;